n1 = int(input("digite o primeiro numero inteiro: "))
n2 = int(input("digite o segundo numero inteiro: "))
s = n1 + n2
sb = n1 - n2
m = n1 * n2
d = n1 / n2
print(f"soma= {s}")
print(f"subtração= {sb}")
print(f"multiplicação= {m}")
print(f"divisão= {d}")